TestCentric/testcentric-experimental-gui

- src/nunit-gui/Presenters/XmlPresenter.cs
- src/nunit-gui/Program.cs
- src/nunit-gui/Views/MainForm.Designer.cs
- src/nunit-gui/Views/MainForm.cs
- src/nunit-gui/Views/XmlView.Designer.cs
- src/nunit-gui/Views/XmlView.cs
- src/nunit-gui/Views/XmlView.resx
- src/nunit-gui/XmlHelper.cs
- src/nunit-gui/nunit-gui.csproj
Do not merge yet.
Fixes #68 <== This gives us a link to the issue plus a backlink from the issue to this PR.
> Fixes #68 

- CHANGES.txt
- build.cake
- nunit-gui.sln
This will complete the 0.1 release when merged. This release is only intended for review of the UI, not for use in production.
> Release 0.1

- src/nunit-gui/App.config
> Fix App.config so we run under highest available runtime version

- CHANGES.txt
- LICENSE
- build.cake
- src/nunit-gui/Properties/AssemblyInfo.cs
- src/nunit.uikit/Properties/AssemblyInfo.cs
- src/tests/Properties/AssemblyInfo.cs
> Prepare for 0.2 release

- src/mock-assembly/mock-assembly.csproj
- src/mock-assembly/packages.config
- src/nunit-gui/nunit-gui.csproj
- src/nunit-gui/packages.config
- src/tests/Model/TestModelTests.cs
- src/tests/nunit-gui.tests.csproj
- src/tests/packages.config
issue#108
this does not fix the issue stated, but it is where the idea was planted in my head to update (granted we talked about it in a differen thead)
This pull request simply is just to update to the latest version of NUnit Framework and Engine. However I feel like maybe a slight discussion should take place about this because I feel like a better way to do this would be to use a submodule. Then I could point to specific commits in there if say I want to pull in a fix. I'm not sure how the build server would like it though. I suppose one way to find out.
> updated project to use latest NUnit.Engine and Framework.

- src/nunit-gui/Presenters/AddinsPresenter.cs
- src/nunit-gui/Presenters/MainPresenter.cs
- src/nunit-gui/Views/AddinPages/AddinsView.Designer.cs
- src/nunit-gui/Views/AddinPages/AddinsView.cs
- src/nunit-gui/Views/AddinPages/AddinsView.resx
- src/nunit-gui/Views/AddinPages/ExtensionNodeView.cs
- src/nunit-gui/Views/AddinPages/ExtensionPointView.cs
- src/nunit-gui/Views/IAddinsView.cs
- src/nunit-gui/Views/IDialog.cs
- src/nunit-gui/Views/SettingsDialog.cs
- src/nunit-gui/nunit-gui.csproj
- src/tests/Presenters/AddinsPresenterTests.cs
- src/tests/Views/CommonViewTests.cs
- src/tests/nunit-gui.tests.csproj
> Added an extensions dialog to see what current extensions are in use.

- build.cake
- src/mock-assembly/mock-assembly.csproj
- src/mock-assembly/packages.config
- src/nunit-gui/Model/TestModel.cs
- src/nunit-gui/nunit-gui.csproj
- src/nunit-gui/packages.config
- src/tests/nunit-gui.tests.csproj
- src/tests/packages.config
- tools/packages.config
All packages are now up to date.
> Update package references to latest versions

- src/nunit-gui/Model/TestModel.cs
> Temporary thread to allow use of blocking Run

- src/nunit-gui/Model/Settings/EngineSettings.cs
- src/nunit-gui/Model/Settings/GuiSettings.cs
- src/nunit-gui/Model/Settings/TestTreeSettings.cs
Additional code removal for #86
> Remove additional code for unused settings

- CHANGES.txt
- build.cake
- src/mock-assembly/MockAssembly.cs
* Update changes file
* Drop source zip (since github does it)
* Standardize pre-release suffixes
> Prepare for 0.3 release

- src/nunit-gui/CommandLineOptions.cs
- src/nunit-gui/Model/ResultState.cs
- src/nunit-gui/Model/TestAction.cs
- src/nunit-gui/Model/TreeDisplayStyle.cs
- src/nunit-gui/Presenters/FixtureListDisplayStrategy.cs
- src/nunit-gui/Views/TestTreeView.cs
- src/tests/XmlRtfConverterTests.cs
Continuing nunit/nunit#1960, just a couple changes.
[One is in some dead code. Can I remove it?](https://github.com/nunit/nunit-gui/pull/153/files#r95192666)
/cc @CharliePoole @ChrisMaddock
> Typo fixes

- src/nunit-gui/Xml2RtfConverter.cs
- src/tests/XmlRtfConverterTests.cs
> Escape the content of CDATA

- build.cake
- src/mock-assembly/mock-assembly.csproj
- src/mock-assembly/packages.config
- src/nunit-gui/nunit-gui.csproj
- src/nunit-gui/packages.config
- src/tests/nunit-gui.tests.csproj
- src/tests/packages.config
> Upgrade to framework and engine versions 3.6.1

- NuGet.config
- build.cake
- src/nunit-gui/nunit-gui.csproj
- src/tests/nunit-gui.tests.csproj
- src/tests/packages.config
- tools/packages.config
Since I merged #177 without waiting for comments, I'm doing a new pr here to deal with @mikkelbu 's suggestions. In addition, I upgraded NSubstitute at the same time.
> Fixes to already merged PR #177

- src/nunit-gui/Presenters/MainPresenter.cs
- src/nunit-gui/Views/IMainView.cs
- src/nunit-gui/Views/MainForm.Designer.cs
It is now possible to drag and drop files into the
main form.
Fixes #155
> Add drag and drop of files

- src/nunit-gui/Model/TestModel.cs
> Default to running out of process; parallel

- src/nunit-gui/nunit-gui.csproj
> Copy nunit-agent.exe and nunit-agent-x86.exe to output

- build.cake
> Add agent files to package

- src/nunit-gui/Model/TestModel.cs
- src/nunit-gui/Views/ProgressBarView.Designer.cs
> Use ShadowCopy to load tests

- build.cake
Just a simple search and replace to make the file consistent 
(and to show properly in editors - or on github - where tab != 4 spaces)
> Replace tabs with spaces in cake file

- src/nunit-gui/Views/MainForm.Designer.cs
- src/nunit-gui/Views/MainForm.cs
> fixes drag and drop

- CHANGES.txt
- build.cake
- src/nunit-gui/Properties/AssemblyInfo.cs
- src/nunit-gui/nunit-gui.csproj
- src/nunit-gui/nunit.engine.addins
- src/nunit.uikit/Properties/AssemblyInfo.cs
This PR updates the CHANGES file and changes version numbers for the release. If there is anything missing that should be included in the release, please add comment.
I expressly held back any changes to how the files are organized for after the release.
> Prepare for release 0.4

- README.md
> Added link to releases page.

- build.cake
- choco/nunit-gui.nuspec
- choco/nunit.choco.addins
> Create chocolatey package

- CHANGES.txt
- build.cake
- src/nunit-gui/Properties/AssemblyInfo.cs
- src/nunit.uikit/Properties/AssemblyInfo.cs
> Prepare for 0.5 Release

- src/nunit-gui/Presenters/MainPresenter.cs
- src/nunit.uikit/IMessageDisplay.cs
- src/nunit.uikit/MessageDisplay.cs
- src/nunit.uikit/nunit.uikit.csproj
Continued work on issue #189. I'm doing this a bit at a time in order to get things committed quickly and avoid conflicts.
> Remove Windows references from IMessageDisplay

- src/nunit-gui/Presenters/MainPresenter.cs
- src/nunit-gui/Views/MainForm.cs
- src/nunit.gui.core/Views/IMainView.cs
Continued work on issue #189. I'm doing this a bit at a time in order to get things committed quickly and avoid conflicts.
> Issue 189c

- src/nunit-gui/Presenters/DisplayStrategy.cs
- src/nunit-gui/Presenters/FixtureListDisplayStrategy.cs
- src/nunit-gui/Presenters/MainPresenter.cs
- src/nunit-gui/Presenters/NUnitTreeDisplayStrategy.cs
- src/nunit-gui/Presenters/TestListDisplayStrategy.cs
- src/nunit-gui/Presenters/TreeViewPresenter.cs
- src/nunit-gui/Settings/EngineSettings.cs
- src/nunit-gui/Settings/GuiSettings.cs
- src/nunit-gui/Settings/SettingsGroup.cs
- src/nunit-gui/Settings/SettingsModel.cs
- src/nunit-gui/Settings/TestTreeSettings.cs
- src/nunit-gui/Settings/TreeDisplayStyle.cs
- src/nunit-gui/Views/SettingsDialog.cs
- src/nunit-gui/Views/SettingsPage.cs
- src/nunit-gui/Views/SettingsPages/AssemblyReloadSettingsPage.cs
- src/nunit-gui/Views/SettingsPages/GuiSettingsPage.cs
- src/nunit-gui/nunit-gui.csproj
- src/nunit.gui.core/Model/ITestModel.cs
- src/nunit.gui.core/Model/TestModel.cs
- src/nunit.gui.core/Views/ISettingsDialog.cs
- src/nunit.gui.core/nunit.gui.core.csproj
- src/tests/Presenters/Main/CommandTests.cs
- src/tests/Presenters/TestTree/NUnitTreeDisplayStrategyTests.cs
- src/tests/Presenters/TestTree/TestTreePresenterTestBase.cs
- src/tests/Presenters/TreeViewPresenterTests.cs
- src/tests/Presenters/UserSettingsFake.cs
Continuing isolation of model... partial fix to #189
> Move settings out of model

- .gitignore
- src/nunit-gui/Presenters/MainPresenter.cs
- src/nunit-gui/Views/MainForm.cs
- src/nunit.gui.core/Model/ITestModel.cs
- src/nunit.gui.core/Model/TestEventArgs.cs
- src/nunit.gui.core/Model/TestModel.cs
- src/nunit.gui.core/Views/IMainView.cs
- src/nunit.uikit/Controls/LongRunningOperationDisplay.cs
- src/nunit.uikit/nunit.uikit.csproj
- src/tests/Presenters/Main/WhenTestsAreLoaded.cs
- src/tests/Presenters/Main/WhenTestsAreLoading.cs
- src/tests/nunit-gui.tests.csproj
> Issue 96 show notification of assemblies loading

- src/nunit.gui.core/Model/TestModel.cs
- src/tests/Model/AvailableRuntimesTest.cs
- src/tests/nunit-gui.tests.csproj
Fixes #209 (again)
I'm going to come back to this to add some more tests and refactor a bit, but let's get the fix merged so we are not blowing up when the GUI starts.
> Fix NRE in AvailableRuntimes

- src/nunit-gui/Presenters/DisplayStrategy.cs
- src/nunit-gui/Presenters/MainPresenter.cs
- src/nunit-gui/Presenters/TreeViewPresenter.cs
- src/nunit.testmodel/Model/ITestModel.cs
- src/nunit.testmodel/Model/ITestServices.cs
- src/nunit.testmodel/Model/TestModel.cs
- src/nunit.testmodel/Model/TestServices.cs
- src/nunit.testmodel/nunit.testmodel.csproj
> Organize Services under Services property

- src/TestCentric/testcentric.gui/Presenters/MainPresenter.cs
- src/TestCentric/tests/Presenters/Main/WhenTestsAreLoading.cs
- src/TestCentric/tests/TestCentric.Gui.Tests.csproj
- src/TestCentric/tests/XmlRtfConverterTests.cs
- src/TestCentric/tests/packages.config
- src/tests/demo-assembly/demo-assembly.csproj
- src/tests/demo-assembly/packages.config
- src/tests/mock-assembly/mock-assembly.csproj
- src/tests/mock-assembly/packages.config
> Upgrade nunit framework to 3.11

- build.cake
- src/TestCentric/testcentric.gui/TestCentric.Gui.csproj
- src/TestCentric/testcentric.gui/packages.config
- src/TestCentric/tests/TestCentric.Gui.Tests.csproj
- src/TestCentric/tests/packages.config
- src/TestModel/model/TestCentric.Gui.Model.csproj
- src/TestModel/model/packages.config
> Update experimental GUI to NUnit Engine 3.9

- src/TestCentric/components/Controls/LongRunningOperationDisplay.cs
- src/TestCentric/components/Controls/TipWindow.cs
- src/TestCentric/components/Elements/CheckedMenuGroup.cs
- src/TestCentric/components/Elements/ControlElement.cs
- src/TestCentric/components/Elements/IViewElement.cs
- src/TestCentric/components/Elements/ToolStripElement.cs
- src/TestCentric/tests/Views/CommonViewTests.cs
Part of #276 
Included
* Remove Name property from IViewElement
* Minor refactoring
> Miscellaneous modifications for compatibility with standard GUI

- src/TestCentric/components/Elements/CheckBoxElement.cs
- src/TestCentric/components/Elements/CheckedMenuGroup.cs
- src/TestCentric/components/Elements/ICommand.cs
- src/TestCentric/components/Elements/IMenu.cs
- src/TestCentric/components/Elements/ITreeView.cs
- src/TestCentric/components/Elements/MenuElement.cs
- src/TestCentric/components/Elements/TreeViewElement.cs
- src/TestCentric/components/TestCentric.Gui.Components.csproj
- src/TestCentric/testcentric.gui/Presenters/DisplayStrategy.cs
- src/TestCentric/testcentric.gui/Views/ITestTreeView.cs
- src/TestCentric/testcentric.gui/Views/TestTreeView.cs
This is the filan PR that fixes #276
> Miscellaneous changes to match standard GUI

- CHANGES.txt
- build.cake
- src/CommonAssemblyInfo.cs
This is the 0.7 release, which will be published from master once it is merged.
> Release 0.7
