TestCentric/testcentric-experimental-gui

- src/nunit-gui/Model/ITestItem.cs
- src/nunit-gui/Model/ITestModel.cs
- src/nunit-gui/Model/TestEventArgs.cs
- src/nunit-gui/Model/TestModel.cs
- src/nunit-gui/Presenters/MainPresenter.cs
- src/nunit-gui/Presenters/StatusBarPresenter.cs
- src/nunit-gui/Presenters/TestPropertiesPresenter.cs
- src/nunit-gui/Presenters/TreeViewPresenter.cs
- src/nunit-gui/Presenters/XmlPresenter.cs
- src/tests/Model/TestModelTests.cs
- src/tests/Presenters/Main/WhenTestRunBegins.cs
- src/tests/Presenters/Main/WhenTestRunCompletes.cs
- src/tests/Presenters/Main/WhenTestsAreLoaded.cs
- src/tests/Presenters/Main/WhenTestsAreReloaded.cs
- src/tests/Presenters/ProgressBarPresenterTests.cs
- src/tests/Presenters/StatusBarPresenterTests.cs
- src/tests/Presenters/TestTree/CommandTests.cs
- src/tests/Presenters/TestTree/WhenTestRunBegins.cs
- src/tests/Presenters/TestTree/WhenTestRunCompletes.cs
- src/tests/Presenters/TestTree/WhenTestsAreLoaded.cs
- src/tests/Presenters/TestTree/WhenTestsAreReloaded.cs
- src/tests/Presenters/TreeViewPresenterTests.cs
The selected test node in the tree did not really belong in the model as it's part of the presentation logic. This PR  takes care of the problem.
* Created more event handler delegates and event argument types, so events will be a bit more type-safe than they were. Discovered some errors in the code in the process.
* Eliminated SelectedTest as a model property.
* Added a model method NotifySelectedTestItemChanged, which causes the model to re-broadcast a change discovered by one of the presenters so that other presenters can handle it.
* Each presenter that uses the selected item independently maintains a field with the current selection.
I plan to follow the rule of three here. That is, if we find a second event that needs to be handled by multiple presenters, I'll just add an event and …
> Changes to selected test processing

- src/nunit-gui/Model/ITestModel.cs
- src/nunit-gui/Model/TestModel.cs
- src/nunit-gui/Presenters/MainPresenter.cs
Implementation is rudimentary but works. Needs to be refactored to eliminate use of engine class RuntimeFramework if possible.
> Load tests under selected runtime. Fixes #44

- src/nunit-gui/Program.cs
This fixes issue #93 by forcing the Gui to use the bundled copy of the engine.
> Use only private copy of engine.

- src/nunit-gui/Presenters/CategoryGrouping.cs
When viewing testcases by category, only the first test of each case gets listed under the correct category, everything else defaults to Category None (via the groups.Add(Groups[0]) line above), even if an existing group was found with the required name.
> Bug Fix when viewing by category

- src/nunit-gui/Model/ResultNode.cs
- src/tests/Model/ResultNodeTests.cs
- src/tests/nunit-gui.tests.csproj
Fixes #117.
Inside `InitializeResultProperties` changed to `double.Parse` overload with culture parameter usage, so it will parse using `CultureInfo.InvariantCulture` and thus won't throw `System.FormatException` on systems that use different from '.' (dot) decimal delimiter in their culture, e.g. ',' (comma).
> When initializing ResultNode use CultureInfo.InvariantCulture for parsing `duration` attribute value

- src/nunit-gui/Views/SettingsPages/AdvancedEngineSettingsPage.Designer.cs
- src/nunit-gui/Views/SettingsPages/AdvancedEngineSettingsPage.cs
- src/nunit-gui/Views/SettingsPages/AssemblyIsolationSettingsPage.Designer.cs
- src/nunit-gui/Views/SettingsPages/GuiSettingsPage.Designer.cs
- src/nunit-gui/Views/SettingsPages/ProjectEditorSettingsPage.Designer.cs
- src/nunit-gui/Views/SettingsPages/RuntimeSelectionSettingsPage.Designer.cs
- src/nunit-gui/Views/SettingsPages/TreeSettingsPage.Designer.cs
This is a preliminary step toward resolving issue #86. The settings we do not currently support are disabled in the panels to make their status more visible.
> Disable items in settings panels, which we don't plan to use.

- NuGet.config
- nunit-gui.sln
Fixes #126 
This adds a NUget.config file pointing to the nunit-gui-team feed on myget. We'll use this feed for package references that override the standard packages in nuget.org, particularly for the engine.
> Use new Gui Team Feed as nuget source

- NuGet.config
- build.cake
- src/nunit-gui/Model/TestModel.cs
- src/nunit-gui/nunit-gui.csproj
- src/nunit-gui/packages.config
- src/tests/nunit-gui.tests.csproj
- src/tests/packages.config
This fix makes use of a pre-release build of NUnit Engine 3.6 to avoid creating a window when launching the agent process. It also fixes a problem that prevented use of RunAsync in the gui when running tests.
> Eliminate console window display when running in separate process

- src/nunit-gui/CommandLineOptions.cs
- src/nunit-gui/Program.cs
The method RequiredValue is changed to match the same
method in nunit-console project, hence we now support
values that differ in casing (and RequiredValue corrects
the casing).
Furthermore, the options are now validated, and a
messagebox is presented to the user if the options
are invalid.
Fixes #163
> Parsing and validation of options

- src/nunit-gui/Presenters/TestPropertiesPresenter.cs
Message and StackTrace are now reset to "" if the
test does not contain a "message"/"stack-trace"
XML node, repectively.
Fixes #173
> Update Message and StackTrace

- tools/packages.config
Make nunit-gui use the same version of Cake as nunit-console to
make it possible to compile the project on a computer with
only VS 2017 installed.
Fixes #179
> Lift Cake version to 0.19.1

- src/nunit-gui/Views/SettingsPage.cs
Otherwise, we could end up in a situation where ApplySettings
is called even if LoadSettings is not called.
Fixes #130
> SettingsLoaded only true after LoadSettings call

- src/nunit-gui/Model/ITestModel.cs
- src/nunit-gui/Model/TestModel.cs
- src/nunit-gui/Presenters/MainPresenter.cs
- src/nunit-gui/Presenters/XmlPresenter.cs
- src/nunit-gui/Views/IMainView.cs
- src/nunit-gui/Views/MainForm.Designer.cs
- src/nunit-gui/Views/MainForm.cs
- src/nunit-gui/Views/TestTreeView.cs
- src/nunit-gui/Views/XmlView.cs
- src/nunit.uikit/Elements/CheckedMenuGroup.cs
- src/nunit.uikit/Elements/IMenu.cs
- src/nunit.uikit/Elements/IPopup.cs
- src/nunit.uikit/Elements/ISelection.cs
- src/nunit.uikit/Elements/IToolStripElement.cs
- src/nunit.uikit/Elements/MenuElement.cs
- src/nunit.uikit/Elements/ToolStripElement.cs
- src/nunit.uikit/IMessageDisplay.cs
- src/nunit.uikit/MessageDisplay.cs
- src/nunit.uikit/nunit.uikit.csproj
- src/tests/Model/TestModelAssemblyTests.cs
- src/tests/Model/TestModelPackageTests.cs
- src/tests/Presenters/Main/PackageSettingsTests.cs
- src/tests/Presenters/Main/WhenPresenterIsCreated.cs
- src/tests/Presenters/Main/WhenTestRunBegins.cs
- src/tests/Presenters/Main/WhenTestRunCompletes.cs
- src/tests/Presenters/Main/WhenTestsAreLoaded.cs
- src/tests/Presenters/Main/WhenTestsAreReloaded.cs
- src/tests/Presenters/Main/WhenTestsAreUnloaded.cs
- src/tests/Views/MainFormTests.cs
- src/tests/nunit-gui.tests.csproj
Fixes #154 
I'm pretty sure this isn't the last word on the subject, especially WRT the UI. However, it works and is ready for code review and merging so that people can use the various load settings. I still have to hook up the X86 option, but I thought it should start getting reviewed.
After discussing putting it elsewhere, I ended up leaving all three menu items on the File menu. The Process menu is invisible until after a test is loaded. Right now none of the three (Selected Runtime, ProcessModel and DomainUsage actually cause a reload. When you change one you get asked if you want to reload now. You can say no and go back to change another one. However, if it looks like that will happen often, we might want to put all of these settings into a dialog. Main thing for now is that they …
> Allow changing ProcessModel and DomainUsage

- src/nunit-gui/Presenters/ProgressBarPresenter.cs
- src/nunit-gui/Views/MainForm.Designer.cs
- src/nunit-gui/Views/ProgressBarView.Designer.cs
- src/nunit-gui/Views/ProgressBarView.cs
- src/tests/Presenters/ProgressBarPresenterTests.cs
See comment on issue #75 as to why this is being backed out.
@immeraufdemhund In addtion to my comments on the issue, I noticed in looking at the code that you have the view referencing the model, which breaks the WPF pattern, especially if we want to substitute different views at any time. This is an easy mistake to make if the components are all in the same assembly, so maybe we need some separation.
> Back out text progress notices from ProgressBar

- nunit-gui.sln
- src/demo-assembly/ApartmentTests.cs
- src/demo-assembly/App.config
- src/demo-assembly/AsyncTests.cs
- src/demo-assembly/ConfigFileTests.cs
- src/demo-assembly/ExpectedOutcomeAttributes.cs
- src/demo-assembly/GenericTests.cs
- src/demo-assembly/InheritedTestTests.cs
- src/demo-assembly/OneTimeSetUpTests.cs
- src/demo-assembly/ParameterizedTests.cs
- src/demo-assembly/Properties/AssemblyInfo.cs
- src/demo-assembly/SetUpFixtureTests.cs
- src/demo-assembly/SimpleTests.cs
- src/demo-assembly/TextOutputTests.cs
- src/demo-assembly/Theories.cs
- src/demo-assembly/demo-assembly.csproj
- src/demo-assembly/packages.config
- src/nunit-gui/Model/ResultNode.cs
- src/nunit-gui/Model/TestNode.cs
- src/nunit-gui/Presenters/TestPropertiesPresenter.cs
- src/nunit-gui/Views/MainForm.Designer.cs
- src/nunit-gui/Views/TestPropertiesView.Designer.cs
- src/nunit-gui/Views/TestPropertiesView.cs
- src/nunit.uikit/Controls/TipWindow.cs
Fixes #140
I combined the two fields Message and StackTrace on the TestPropertiesView and I'm displaying all the results found. The display could use some color or at least bold fonts but I don't want to do it until we resolve whether we are keeping the ExpandingLabel control, because it will be done differently depending on whether we keep or drop it. I did improve the TipWindow display a little bit.
For testing this, if you want to see it work. the NUnit 3 adapter demo program is a good choice as it has a number of tests with multiple failing asserts, failures plus warnings and failures plus errors.
> Multiple assert support

- src/nunit-gui/Presenters/XmlPresenter.cs
- src/nunit-gui/nunit-gui.csproj
- src/nunit-gui/packages.config
- src/nunit.gui.core/EnginePackageSettings.cs
- src/nunit.gui.core/Model/ITestModel.cs
- src/nunit.gui.core/Model/TestModel.cs
- src/nunit.gui.core/XmlHelper.cs
- src/nunit.gui.core/nunit.gui.core.csproj
- src/nunit.gui.core/packages.config
Fixes #209 
The GUI no longer uses the `RuntimeFramework` type but instead accesses the `IAvailableRuntimes` service. As a result, the reference to the engine itself has been removed from both the `nunit.gui.core` and `nunit-gui` projects.
> Eliminate direct use of engine for runtime frameworks

- src/nunit-gui/Presenters/XmlPresenter.cs
- src/nunit-gui/Views/IXmlView.cs
- src/nunit-gui/Views/MainForm.Designer.cs
- src/nunit-gui/Views/MainForm.cs
- src/nunit-gui/Views/XmlView.cs
TestXml is now set when:
* We change from the tab "Properties" to the tab "XML"
* Or when the tab "XML" is visible and the selected item in the tree changes
This improves the performance of most operations in the gui
(i.e. all operations as long as the "XML" tab is not selected). The only
downside is that going back and forth between the tabs will retrigger
a call to `DisplayXml`.
To improve the experience even more `GetFullXml` and `XmlHelper.ToRtfString`
could be done asynchronous and results could be cached.
Relates to #241
> Only set TestXml when relevant

- src/nunit-gui/Presenters/TestPropertiesPresenter.cs
Note that we currently do not show top-level failures
(a failure-node just inside the outermost test-suite-node)
in the GUI (except in the XML tab), but at least the GUI
does not crash anymore.
Relates to #228 and #184
> Avoid "The path is not of a legal form" GUI crash

- src/nunit-gui/Presenters/MainPresenter.cs
- src/nunit-gui/Presenters/ProgressBarPresenter.cs
- src/nunit-gui/Presenters/StatusBarPresenter.cs
- src/nunit-gui/Presenters/TestPropertiesPresenter.cs
- src/nunit-gui/Presenters/TreeViewPresenter.cs
- src/nunit-gui/Presenters/XmlPresenter.cs
- src/nunit-gui/nunit-gui.csproj
- src/nunit.testmodel/Model/ITestEvents.cs
- src/nunit.testmodel/Model/ITestModel.cs
- src/nunit.testmodel/Model/TestEventArgs.cs
- src/nunit.testmodel/Model/TestEventDispatcher.cs
- src/nunit.testmodel/Model/TestModel.cs
- src/nunit.testmodel/nunit.testmodel.csproj
- src/tests/Presenters/Main/WhenTestRunBegins.cs
- src/tests/Presenters/Main/WhenTestRunCompletes.cs
- src/tests/Presenters/Main/WhenTestsAreLoaded.cs
- src/tests/Presenters/Main/WhenTestsAreLoading.cs
- src/tests/Presenters/Main/WhenTestsAreReloaded.cs
- src/tests/Presenters/Main/WhenTestsAreUnloaded.cs
- src/tests/Presenters/ProgressBarPresenterTests.cs
- src/tests/Presenters/StatusBarPresenterTests.cs
- src/tests/Presenters/TestTree/WhenTestRunBegins.cs
- src/tests/Presenters/TestTree/WhenTestRunCompletes.cs
- src/tests/Presenters/TestTree/WhenTestsAreLoaded.cs
- src/tests/Presenters/TestTree/WhenTestsAreReloaded.cs
- src/tests/Presenters/TestTree/WhenTestsAreUnloaded.cs
- src/tests/Presenters/TreeViewPresenterTests.cs
- src/tests/nunit-gui.tests.csproj
This makes the ITestEvent interface match that of the TestCentric GUI and uses a separate dispatcher to implement the interface. This change is part of issue #249.
> Modify test event handling

- build.cake
- src/TestCentric/tests/Views/CommonViewTests.cs
- src/TestCentric/tests/Views/MainFormTests.cs
Up to now, we didn't run tests in Travis at all.There were only a few fixes having to do with Newline plus a large number of tests of the Views that create the view classes without properly initializing them. This works for our tests in Windows but not Linux.
> Run tests under Travis CI

- .travis.yml
- build.cake
- src/TestCentric/tests/Views/MainFormTests.cs
This works around a bug whereby Cake can't find msbuild on Linux. If we want this to work on OsX, then further changes would be needed.
> Fix build to use MsBuild under Mono 5 or greater

- build.cake
- experimental-gui.sln
- src/tests/mock-assembly/mock-assembly.csproj
We run tests of the GUI using the NUnit3 Cake extension. Currently it's set up to use the 3.7 version of the console. This updates it to use 3.9.
> Use console 3.9

- src/TestCentric/components/Elements/ICommand.cs
Part of #276 
The property was duplicated in both ICommand and IToolStripElement
> Remove ToolTipText prop from ICommand

- src/TestCentric/components/Elements/ICommand.cs
Part of #276 
Property was defined in both ICommand and ICommand<T>
> Remove additional definition of ToolTipText property

- src/TestCentric/testcentric.gui/Presenters/TestPropertiesPresenter.cs
Fixes #282 
The only way I have been able to make it work is to always display the result panel on Linux. It's a hack but I don't think there's any harm to showing the empty panel when there are no results.
> Kluge to make results display on Linux
